[package]
name = "pong-rs"
version = "0.1.0"
authors = ["Ahmad <ahmad.baa003@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"